packages:
  - "packages/*"
  - "docs"
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@umwelt-data/umwelt-utils@0.1.1'
  - '@umwelt-data/umwelt-utils@0.2.0'
  - olli@3.0.1
  - olli@3.1.1
